[GetHashKey('dm1200')] = { model = 'dm1200', price = 1300000, banned = false, name = 'Ducati', trunk = 30, type = 'moto'},
[GetHashKey('urus')] = { model = 'urus', price = 300000, banned = false, name = 'Lamborghini Urus', trunk = 140, type = 'vip'},
[GetHashKey('440i')] = { model = '440i', price = 300000, banned = false, name = 'BMW 440i', trunk = 100, type = 'vip'},
[GetHashKey('gle')] = { model = 'gle', price = 300000, banned = false, name = 'Mercedes GLE', trunk = 200, type = 'vip'},
[GetHashKey('nh2r')] = { model = 'nh2r', price = 2000000, banned = false, name = 'Kawasaki Ninja H2', trunk = 30, type = 'moto'},
[GetHashKey('vwtdiv6')] = { model = 'vwtdiv6', price = 2300000, banned = false, name = 'VW Touareg', trunk = 100, type = 'carro'},
[GetHashKey('nissanskyliner34')] = { model = 'nissanskyliner34', price = 1800000, banned = false, name = 'Skyline R34', trunk = 100, type = 'vip'},
[GetHashKey('sanchez')] = { model = 'sanchez', price = 150000, banned = false, name = 'Sanchez', trunk = 30, type = 'moto'},
[GetHashKey('cheetah')] = { model = 'cheetah', price = 300000, banned = false, name = 'Cheetah', trunk = 100, type = 'carro'},
[GetHashKey('serrano')] = { model = 'serrano', price = 300000, banned = false, name = 'Serrano', trunk = 100, type = 'carro'},
[GetHashKey('faggio')] = { model = 'faggio', price = 15000, banned = false, name = 'Faggio Sport', trunk = 30, type = 'moto'},
[GetHashKey('avarus')] = { model = 'avarus', price = 300000, banned = false, name = 'Avarus', trunk = 30, type = 'moto'},
[GetHashKey('mesa')] = { model = 'mesa', price = 40000, banned = false, name = 'Canis Mesa', trunk = 100, type = 'carro'},
[GetHashKey('tailgater')] = { model = 'tailgater', price = 200000, banned = false, name = 'Tailgater', trunk = 100, type = 'carro'},
[GetHashKey('premier')] = { model = 'premier', price = 150000, banned = false, name = 'Premier', trunk = 100, type = 'carro'},
[GetHashKey('fugitive')] = { model = 'fugitive', price = 35000, banned = false, name = 'Fugitive', trunk = 100, type = 'carro'},
[GetHashKey('nissangtr')] = { model = 'nissangtr', price = 300000, banned = false, name = 'Nissan GTR', trunk = 100, type = 'vip'},
[GetHashKey('kuruma')] = { model = 'kuruma', price = 250000, banned = false, name = 'Kuruma', trunk = 100, type = 'carro'},
[GetHashKey('zentorno')] = { model = 'zentorno', price = 750000, banned = false, name = 'Zentorno', trunk = 100, type = 'carro'},
[GetHashKey('gargoyle')] = { model = 'gargoyle', price = 40000, banned = false, name = 'Gargoyle', trunk = 30, type = 'moto'},
[GetHashKey('fq2')] = { model = 'fq2', price = 400000, banned = false, name = 'Fhantom Q2', trunk = 100, type = 'carro'},
[GetHashKey('akuma')] = { model = 'akuma', price = 800000, banned = false, name = 'Akuma', trunk = 30, type = 'moto'},
[GetHashKey('weevil')] = { model = 'weevil', price = 65000, banned = false, name = 'Fusca', trunk = 130, type = 'carro'},
[GetHashKey('windsor2')] = { model = 'windsor2', price = 70000, banned = false, name = 'Windsor 2', trunk = 130, type = 'carro'},
[GetHashKey('guardian')] = { model = 'guardian', price = 200000, banned = false, name = 'Tracktor Guardain', trunk = 70, type = 'carro'},
[GetHashKey('deviant')] = { model = 'deviant', price = 75000, banned = false, name = 'Deviant', trunk = 130, type = 'carro'},
[GetHashKey('coquette3')] = { model = 'coquette3', price = 750000, banned = false, name = 'Coquette 3', trunk = 130, type = 'carro'},
[GetHashKey('yosemite')] = { model = 'yosemite', price = 500000, banned = false, name = 'Yosemite', trunk = 50, type = 'carro'},
[GetHashKey('yosemite3')] = { model = 'yosemite3', price = 550000, banned = false, name = 'Yosemite 3', trunk = 50, type = 'carro'},
[GetHashKey('blade')] = { model = 'blade', price = 500, banned = false, name = 'Blade', trunk = 130, type = 'carro'},
[GetHashKey('ellie')] = { model = 'ellie', price = 300000, banned = false, name = 'Ellie', trunk = 130, type = 'carro'},
[GetHashKey('gauntlet3')] = { model = 'gauntlet3', price = 500000, banned = false, name = 'Gauntlet 3', trunk = 130, type = 'carro'},
[GetHashKey('impaler')] = { model = 'impaler', price = 750000, banned = false, name = 'Impaler', trunk = 130, type = 'carro'},
[GetHashKey('slamvan3')] = { model = 'slamvan3', price = 450000, banned = false, name = 'Slamvan 3', trunk = 70, type = 'carro'},
[GetHashKey('vamos')] = { model = 'vamos', price = 500000, banned = false, name = 'Vamos ', trunk = 130, type = 'carro'},
[GetHashKey('cog55')] = { model = 'cog55', price = 650000, banned = false, name = 'Cog 55', trunk = 130, type = 'carro'},
[GetHashKey('carbonizzare')] = { model = 'carbonizzare', price = 800000, banned = false, name = 'Carbonizzare', trunk = 130, type = 'carro'},
[GetHashKey('comet5')] = { model = 'comet5', price = 550000, banned = false, name = 'Comet 5', trunk = 130, type = 'carro'},
[GetHashKey('coquette4')] = { model = 'coquette4', price = 550000, banned = false, name = 'Coquette 4', trunk = 130, type = 'carro'},
[GetHashKey('drafter')] = { model = 'drafter', price = 350000, banned = false, name = 'Drafter', trunk = 130, type = 'carro'},
[GetHashKey('komoda')] = { model = 'komoda', price = 500000, banned = false, name = 'Komoda', trunk = 130, type = 'carro'},
[GetHashKey('italigto')] = { model = 'italigto', price = 850000, banned = false, name = 'ItaliGTO', trunk = 130, type = 'carro'},
[GetHashKey('jugular')] = { model = 'jugular', price = 750000, banned = false, name = 'Jugular', trunk = 130, type = 'carro'},
[GetHashKey('neon')] = { model = 'neon', price = 850000, banned = false, name = 'Neon', trunk = 130, type = 'carro'},
[GetHashKey('paragon')] = { model = 'paragon', price = 550000, banned = false, name = 'Paragon', trunk = 130, type = 'carro'},
[GetHashKey('schlagen')] = { model = 'schlagen', price = 750000, banned = false, name = 'Schlagen', trunk = 130, type = 'carro'},
[GetHashKey('sugoi')] = { model = 'sugoi', price = 300000, banned = false, name = 'Sugoi', trunk = 130, type = 'carro'},
[GetHashKey('rebla')] = { model = 'rebla', price = 750000, banned = false, name = 'Rebla', trunk = 130, type = 'carro'},
[GetHashKey('novak')] = { model = 'novak', price = 600000, banned = false, name = 'Novak', trunk = 130, type = 'carro'},
[GetHashKey('landstalker2')] = { model = 'landstalker2', price = 850000, banned = false, name = 'Landstalker2', trunk = 130, type = 'carro'},
[GetHashKey('hellion')] = { model = 'hellion', price = 700000, banned = false, name = 'Hellion', trunk = 130, type = 'carro'},
[GetHashKey('kamacho')] = { model = 'kamacho', price = 300000, banned = false, name = 'Kamacho', trunk = 200, type = 'carro'},
[GetHashKey('mesa3')] = { model = 'mesa3', price = 350000, banned = false, name = 'Mesa 3', trunk = 130, type = 'carro'},
[GetHashKey('verus')] = { model = 'verus', price = 200000, banned = false, name = 'Verus', trunk = 50, type = 'moto'},
[GetHashKey('caracara2')] = { model = 'caracara2', price = 350000, banned = false, name = 'Caracara2', trunk = 200, type = 'carro'},
[GetHashKey('vstr')] = { model = 'vstr', price = 700000, banned = false, name = 'Vstr', trunk = 130, type = 'carro'},
[GetHashKey('infernus2')] = { model = 'infernus2', price = 300000, banned = false, name = 'Infernus2', trunk = 130, type = 'carro'},
[GetHashKey('mamba')] = { model = 'mamba', price = 550000, banned = false, name = 'Mamba', trunk = 130, type = 'carro'},
[GetHashKey('thrax')] = { model = 'thrax', price = 1200000, banned = false, name = 'Thrax', trunk = 130, type = 'carro'},
[GetHashKey('zorrusso')] = { model = 'zorrusso', price = 1300000, banned = false, name = 'Zorrusso', trunk = 130, type = 'carro'},
[GetHashKey('visione')] = { model = 'visione', price = 2000000, banned = false, name = 'Visione', trunk = 130, type = 'carro'},
[GetHashKey('vagner')] = { model = 'vagner', price = 1200000, banned = false, name = 'Vagner', trunk = 130, type = 'carro'},
[GetHashKey('tyrus')] = { model = 'tyrus', price = 5000000, banned = false, name = 'Tyrus', trunk = 130, type = 'carro'},
[GetHashKey('emerus')] = { model = 'emerus', price = 300000, banned = false, name = 'Emerus', trunk = 130, type = 'carro'},
[GetHashKey('pfister811')] = { model = 'pfister811', price = 2000000, banned = false, name = 'Pfister 811', trunk = 130, type = 'carro'},
[GetHashKey('fmj')] = { model = 'fmj', price = 1300000, banned = false, name = 'FMJ', trunk = 130, type = 'carro'},
[GetHashKey('prototipo')] = { model = 'prototipo', price = 800000, banned = false, name = 'Prototipo', trunk = 130, type = 'carro'},
[GetHashKey('osiris')] = { model = 'osiris', price = 1200000, banned = false, name = 'Osiris', trunk = 130, type = 'carro'},
[GetHashKey('krieger')] = { model = 'krieger', price = 800000, banned = false, name = 'Krieger', trunk = 130, type = 'carro'},
[GetHashKey('penetrator')] = { model = 'penetrator', price = 300000, banned = false, name = 'Penetrator', trunk = 130, type = 'carro'},
[GetHashKey('italirsx')] = { model = 'italirsx', price = 2300000, banned = false, name = 'ItaliRSX', trunk = 130, type = 'carro'},
[GetHashKey('xa21')] = { model = 'xa21', price = 1200000, banned = false, name = 'XA21', trunk = 130, type = 'carro'},
[GetHashKey('furia')] = { model = 'furia', price = 1200000, banned = false, name = 'Furia', trunk = 130, type = 'carro'},
[GetHashKey('gp1')] = { model = 'gp1', price = 300000, banned = false, name = 'GP1', trunk = 130, type = 'carro'},
[GetHashKey('futo')] = { model = 'futo', price = 150000, banned = false, name = 'Futo', trunk = 130, type = 'carro'},
[GetHashKey('rumpo3')] = { model = 'rumpo3', price = 400000, banned = false, name = 'Rumpo 3', trunk = 300, type = 'carro'},
[GetHashKey('turismor')] = { model = 'turismor', price = 700000, banned = false, name = 'TurismoR', trunk = 130, type = 'carro'},
[GetHashKey('lectro')] = { model = 'lectro', price = 200000, banned = false, name = 'Lectro', trunk = 70, type = 'moto'},
[GetHashKey('sanctus')] = { model = 'sanctus', price = 800000, banned = false, name = 'Sanctus', trunk = 70, type = 'moto'},
[GetHashKey('vortex')] = { model = 'vortex', price = 750000, banned = false, name = 'Vortex', trunk = 70, type = 'moto'},
[GetHashKey('zombieb')] = { model = 'zombieb', price = 1500, banned = false, name = 'ZombieB', trunk = 70, type = 'moto'},
[GetHashKey('hakuchou')] = { model = 'hakuchou', price = 300000, banned = false, name = 'Hakuchou', trunk = 70, type = 'moto'},
[GetHashKey('hakuchou2')] = { model = 'hakuchou2', price = 900000, banned = false, name = 'Hakuchou2', trunk = 70, type = 'moto'},
[GetHashKey('innovation')] = { model = 'innovation', price = 550000, banned = false, name = 'Innovation', trunk = 70, type = 'moto'},
[GetHashKey('wolfsbane')] = { model = 'wolfsbane', price = 400000, banned = false, name = 'Wolfsbane', trunk = 70, type = 'moto'},
[GetHashKey('chimera')] = { model = 'chimera', price = 500000, banned = false, name = 'Chimera', trunk = 70, type = 'moto'},
[GetHashKey('tulip')] = { model = 'tulip', price = 300000, banned = false, name = 'Tulip', trunk = 130, type = 'carro'},
[GetHashKey('seminole2')] = { model = 'seminole2', price = 500000, banned = false, name = 'Seminole 2', trunk = 130, type = 'carro'},
[GetHashKey('bf400')] = { model = 'bf400', price = 200000, banned = false, name = 'BF400', trunk = 70, type = 'moto'},
[GetHashKey(' diablous2')] = { model = ' diablous2', price = 700000, banned = false, name = 'Diablous 2', trunk = 70, type = 'moto'},
[GetHashKey('carbonrs')] = { model = 'carbonrs', price = 300000, banned = false, name = 'Carbonrs', trunk = 70, type = 'moto'},
[GetHashKey('gauntlet4')] = { model = 'gauntlet4', price = 650000, banned = false, name = 'Gauntlet 4', trunk = 130, type = 'carro'},
[GetHashKey('faction2')] = { model = 'faction2', price = 50000, banned = false, name = 'Faction2', trunk = 130, type = 'carro'},
[GetHashKey('buccaneer2')] = { model = 'buccaneer2', price = 500000, banned = false, name = 'Buccaneer 2', trunk = 130, type = 'carro'},
[GetHashKey('chino2')] = { model = 'chino2', price = 400000, banned = false, name = 'Chino 2', trunk = 130, type = 'carro'},
[GetHashKey('moonbeam2')] = { model = 'moonbeam2', price = 400000, banned = false, name = 'Moonbeam2', trunk = 130, type = 'carro'},
[GetHashKey('virgo2')] = { model = 'virgo2', price = 400000, banned = false, name = 'Virgo 2', trunk = 130, type = 'carro'},
[GetHashKey('tornado5')] = { model = 'tornado5', price = 25000, banned = false, name = 'Tornado 5', trunk = 130, type = 'carro'},
[GetHashKey('voodoo')] = { model = 'voodoo', price = 400000, banned = false, name = 'Voodoo', trunk = 130, type = 'carro'},
[GetHashKey('rallytruck')] = { model = 'rallytruck', price = 20000000, banned = false, name = 'Rallytruck', trunk = 1000, type = 'carro'},
[GetHashKey('turismo')] = { model = 'turismo', price = 200000, banned = false, name = 'turismo', trunk = 100, type = 'vip'},
[GetHashKey('elegy')] = { model = 'elegy', price = 300000, banned = false, name = 'Elegy', trunk = 100, type = 'vip'},
[GetHashKey('furia')] = { model = 'furia', price = 300000, banned = false, name = 'furia', trunk = 100, type = 'vip'},
[GetHashKey('taipan')] = { model = 'taipan', price = 300000, banned = false, name = 'taipan', trunk = 100, type = 'vip'},
[GetHashKey('osiris')] = { model = 'osiris', price = 300000, banned = false, name = 'osiris', trunk = 100, type = 'vip'},
[GetHashKey('emereus')] = { model = 'emereus', price = 300000, banned = false, name = 'emereus', trunk = 100, type = 'vip'},
[GetHashKey('sheava')] = { model = 'sheava', price = 300000, banned = false, name = 'sheava', trunk = 100, type = 'vip'},
[GetHashKey('sultanrs')] = { model = 'sultanrs', price = 300000, banned = false, name = 'sultanrs', trunk = 100, type = 'vip'},
[GetHashKey('thrax')] = { model = 'thrax', price = 300000, banned = false, name = 'thrax', trunk = 100, type = 'vip'},
[GetHashKey('visone')] = { model = 'visone', price = 300000, banned = false, name = 'visone', trunk = 100, type = 'vip'},
[GetHashKey('vagner')] = { model = 'vagner', price = 300000, banned = false, name = 'vagner', trunk = 100, type = 'vip'},
[GetHashKey('Tyrant')] = { model = 'Tyrant', price = 300000, banned = false, name = 'Tyrant', trunk = 100, type = 'vip'},
[GetHashKey('skyliner34')] = { model = 'skyliner34', price = 300000, banned = false, name = 'skyliner34', trunk = 100, type = 'vip'},
[GetHashKey('r1')] = { model = 'r1', price = 300000, banned = false, name = 'Yamaha R1', trunk = 50, type = 'vip'},
[GetHashKey('18velar')] = { model = '18velar', price = 300000, banned = false, name = 'Range Rover Velar', trunk = 200, type = 'carro'},
[GetHashKey('718caymans')] = { model = '718caymans', price = 300000, banned = false, name = 'Porsche Caymans', trunk = 200, type = 'vip'},
[GetHashKey('f4rr')] = { model = 'f4rr', price = 300000, banned = false, name = 'F4RR Agusta', trunk = 30, type = 'vip'},
[GetHashKey('cbrr')] = { model = 'cbrr', price = 300000, banned = false, name = 'CB 1000RR', trunk = 30, type = 'vip'},
[GetHashKey('gsrx')] = { model = 'gsrx', price = 300000, banned = false, name = 'Suzuki GSXR1000', trunk = 30, type = 'vip'},
[GetHashKey('hilux2019')] = { model = 'hilux2019', price = 300000, banned = false, name = 'Toyota Hilux 2019', trunk = 170, type = 'carro'},
[GetHashKey('tritonhpe')] = { model = 'tritonhpe', price = 1500000, banned = false, name = 'L200 Triton', trunk = 170, type = 'carro'},
[GetHashKey('aperta')] = { model = 'aperta', price = 300000, banned = false, name = 'Ferrari Aperta', trunk = 100, type = 'vip'},
[GetHashKey('lp700r')] = { model = 'lp700r', price = 300000, banned = false, name = 'Lamborghini Aventador', trunk = 100, type = 'vip'},
[GetHashKey('p1')] = { model = 'p1', price = 300000, banned = false, name = 'MacLaren P1', trunk = 100, type = 'vip'},
[GetHashKey('mgt')] = { model = 'mgt', price = 300000, banned = false, name = 'Mustang GT', trunk = 100, type = 'vip'},
[GetHashKey('velociraptor')] = { model = 'velociraptor', price = 300000, banned = false, name = 'Ranger Velociraptor 6X6', trunk = 200, type = 'vip'},
[GetHashKey('tiger')] = { model = 'tiger', price = 300000, banned = false, name = 'Tiger 800', trunk = 30, type = 'vip'},
[GetHashKey('r1250')] = { model = 'r1250', price = 300000, banned = false, name = 'BMW R1250', trunk = 30, type = 'vip'},
[GetHashKey('s1000rr')] = { model = 's1000rr', price = 300000, banned = false, name = 'BMW S1000RR', trunk = 30, type = 'vip'},
[GetHashKey('opala')] = { model = 'opala', price = 200000, banned = false, name = 'Opala 92/93', trunk = 100, type = 'carro'},
[GetHashKey('evo10')] = { model = 'evo10', price = 300000, banned = false, name = 'Lancer Evolution', trunk = 30, type = 'vip'},
[GetHashKey('lancerevolutionx')] = { model = 'lancerevolutionx', price = 300000, banned = false, name = 'Lancer Evolution X', trunk = 30, type = 'vip'},
[GetHashKey('amggt63s')] = { model = 'amggt63s', price = 300000, banned = false, name = 'Mercedes Amg GT63', trunk = 30, type = 'vip'},
[GetHashKey('488gtb')] = { model = '488gtb', price = 300000, banned = false, name = 'Ferrari 488', trunk = 30, type = 'vip'},
[GetHashKey('r8ppi')] = { model = 'r8ppi', price = 300000, banned = false, name = 'R8', trunk = 30, type = 'vip'},
[GetHashKey('r6')] = { model = 'r6', price = 300000, banned = false, name = 'Yamaha R6', trunk = 30, type = 'vip'},
[GetHashKey('mule')] = { model = 'mule', price = 300000, banned = false, name = 'Mule', trunk = 1500, type = 'vip'},
[GetHashKey('rocoto')] = { model = 'rocoto', price = 500000, banned = false, name = 'Fiat Toro', trunk = 130, type = 'carro'},
[GetHashKey('cavalcade2')] = { model = 'cavalcade2', price = 500000, banned = false, name = 'Parati G3', trunk = 130, type = 'carro'},
[GetHashKey('pcj')] = { model = 'pcj', price = 300000, banned = false, name = 'KTM', trunk = 5, type = 'vip'},
[GetHashKey('mule2')] = { model = 'mule2', price = 300000, banned = false, name = 'Mule2', trunk = 225, type = 'vip'},
[GetHashKey('mule3')] = { model = 'mule3', price = 300000, banned = false, name = 'Mule3', trunk = 300, type = 'vip'},
[GetHashKey('mule4')] = { model = 'mule4', price = 300000, banned = false, name = 'Mule4', trunk = 400, type = 'vip'},
[GetHashKey('havok')] = { model = 'havok', price = 300000, banned = false, name = 'Havok', trunk = 100, type = 'vip'},
[GetHashKey('maverick')] = { model = 'maverick', price = 300000, banned = false, name = 'Maverick', trunk = 100, type = 'vip'},
[GetHashKey('seasparrow')] = { model = 'seasparrow', price = 300000, banned = false, name = 'Seasparrow', trunk = 100, type = 'vip'},
[GetHashKey('Swift')] = { model = 'Swift', price = 300000, banned = false, name = 'Swift', trunk = 100, type = 'vip'},
[GetHashKey('montanaroyal')] = { model = 'montanaroyal', price = 300000, banned = false, name = 'montanaroyal', trunk = 100, type = 'vip'},
[GetHashKey('golfgti7')] = { model = 'golfgti7', price = 300000, banned = false, name = 'golfgti7', trunk = 100, type = 'vip'},
[GetHashKey('savaboxeg7')] = { model = 'savaboxeg7', price = 300000, banned = false, name = 'savaboxeg7', trunk = 100, type = 'vip'},
[GetHashKey('ramlh20')] = { model = 'ramlh20', price = 300000, banned = false, name = 'ramlh20', trunk = 100, type = 'vip'},
[GetHashKey('g7zin')] = { model = 'g7zin', price = 300000, banned = false, name = 'g7zin', trunk = 100, type = 'vip'},
[GetHashKey('s10deboxe')] = { model = 's10deboxe', price = 300000, banned = false, name = 's10deboxe', trunk = 100, type = 'vip'},
[GetHashKey('golg5')] = { model = 'golg5', price = 300000, banned = false, name = 'golg5', trunk = 100, type = 'vip'},
[GetHashKey('golfabel')] = { model = 'golfabel', price = 300000, banned = false, name = 'golfabel', trunk = 100, type = 'vip'},
[GetHashKey('armoredgle')] = { model = 'armoredgle', price = 300000, banned = false, name = 'armoredgle', trunk = 100, type = 'vip'},
[GetHashKey('armoredx6')] = { model = 'armoredx6', price = 300000, banned = false, name = 'armoredx6', trunk = 100, type = 'vip'},
[GetHashKey('silvia')] = { model = 'silvia', price = 300000, banned = false, name = 'silvia', trunk = 100, type = 'vip'},
[GetHashKey('f25')] = { model = 'f25', price = 300000, banned = false, name = 'f25', trunk = 100, type = 'vip'},
[GetHashKey('saveiro')] = { model = 'saveiro', price = 500000, banned = false, name = 'saveiro', trunk = 100, type = 'carro'},
[GetHashKey('hycadem8')] = { model = 'hycadem8', price = 300000, banned = false, name = 'hycadem8', trunk = 100, type = 'vip'},
[GetHashKey('fbi')] = { model = 'fbi', price = 300000, banned = false, name = 'fbi', trunk = 100, type = 'vip'},
[GetHashKey('fbi2')] = { model = 'fbi2', price = 300000, banned = false, name = 'fbi2', trunk = 100, type = 'vip'},
[GetHashKey('policeb')] = { model = 'policeb', price = 300000, banned = false, name = 'policeb', trunk = 100, type = 'vip'},
[GetHashKey('sheriff2')] = { model = 'sheriff2', price = 300000, banned = false, name = 'sheriff2', trunk = 100, type = 'vip'},
[GetHashKey('police4')] = { model = 'police4', price = 300000, banned = false, name = 'police4', trunk = 100, type = 'vip'},
[GetHashKey('stretch')] = { model = 'stretch', price = 300000, banned = false, name = 'stretch', trunk = 100, type = 'vip'},
[GetHashKey('baller5')] = { model = 'baller5', price = 5000000, banned = false, name = 'baller5', trunk = 100, type = 'carro'},
[GetHashKey('baller6')] = { model = 'baller6', price = 8000000, banned = false, name = 'baller6', trunk = 100, type = 'carro'},
[GetHashKey('xls2')] = { model = 'xls2', price = 300000, banned = false, name = 'xls2', trunk = 100, type = 'vip'},
[GetHashKey('patriot2')] = { model = 'patriot2', price = 300000, banned = false, name = 'patriot2', trunk = 100, type = 'vip'},
[GetHashKey('terbyte')] = { model = 'terbyte', price = 300000, banned = false, name = 'terbyte', trunk = 30000, type = 'vip'},
[GetHashKey('pol718')] = { model = 'pol718', price = 300000, banned = false, name = 'porschepolice', trunk = 100, type = 'vip'},
[GetHashKey('ccadeesv')] = { model = 'ccadeesv', price = 300000, banned = false, name = 'ccadeesv', trunk = 100, type = 'vip'},
[GetHashKey('21hilux')] = { model = '21hilux', price = 300000, banned = false, name = '21hilux', trunk = 100, type = 'vip'},
[GetHashKey('21hiluxdimond')] = { model = '21hiluxdimond', price = 300000, banned = false, name = '21hiluxdimond', trunk = 100, type = 'vip'},
[GetHashKey('amarokdeboxe')] = { model = 'amarokdeboxe', price = 300000, banned = false, name = 'amarokdeboxe', trunk = 100, type = 'vip'},
[GetHashKey('fuscaabel')] = { model = 'fuscaabel', price = 300000, banned = false, name = 'fuscaabel', trunk = 100, type = 'carro'},
[GetHashKey('golg8boxeteto')] = { model = 'golg8boxeteto', price = 300000, banned = false, name = 'golg8boxeteto', trunk = 100, type = 'vip'},
[GetHashKey('golgl')] = { model = 'golgl', price = 300000, banned = false, name = 'golgl', trunk = 100, type = 'carro'},
[GetHashKey('porschereb')] = { model = 'porschereb', price = 300000, banned = false, name = 'porschereb', trunk = 100, type = 'vip'},
[GetHashKey('savaboxe')] = { model = 'savaboxe', price = 300000, banned = false, name = 'savaboxe', trunk = 100, type = 'vip'},
[GetHashKey('tcrossar')] = { model = 'tcrossar', price = 300000, banned = false, name = 'tcrossar', trunk = 100, type = 'vip'},
[GetHashKey('r1250')] = { model = 'r1250', price = 300000, banned = false, name = 'r1250', trunk = 100, type = 'vip'},
[GetHashKey('lamborghinihuracan')] = { model = 'lamborghinihuracan', price = 300000, banned = false, name = 'lamborghinihuracan', trunk = 100, type = 'vip'},
[GetHashKey('Wrasprinter')] = { model = 'Wrasprinter', price = 300000, banned = false, name = 'Wrasprinter', trunk = 100, type = 'vip'},
[GetHashKey('Wrgle53')] = { model = 'Wrgle53', price = 300000, banned = false, name = 'Wrgle53', trunk = 100, type = 'vip'},
[GetHashKey('WRr1200')] = { model = 'WRr1200', price = 300000, banned = false, name = 'WRr1200', trunk = 100, type = 'vip'},
[GetHashKey('fnfrx7')] = { model = 'fnfrx7', price = 300000, banned = false, name = 'fnfrx7', trunk = 100, type = 'vip'},
[GetHashKey('fnfmk4')] = { model = 'fnfmk4', price = 300000, banned = false, name = 'fnfmk4', trunk = 100, type = 'vip'},
[GetHashKey('fnflan')] = { model = 'fnflan', price = 300000, banned = false, name = 'fnflan', trunk = 100, type = 'vip'},
[GetHashKey('fnfmits')] = { model = 'fnfmits', price = 300000, banned = false, name = 'fnfmits', trunk = 100, type = 'vip'},
[GetHashKey('ff4wrx')] = { model = 'ff4wrx', price = 300000, banned = false, name = 'ff4wrx', trunk = 100, type = 'vip'},
[GetHashKey('2f2fmle7')] = { model = '2f2fmle7', price = 300000, banned = false, name = '2f2fmle7', trunk = 100, type = 'vip'},
[GetHashKey('2f2fmk4')] = { model = '2f2fmk4', price = 300000, banned = false, name = '2f2fmk4', trunk = 100, type = 'vip'},
[GetHashKey('2f2fgts')] = { model = '2f2fgts', price = 300000, banned = false, name = '2f2fgts', trunk = 100, type = 'vip'},
[GetHashKey('energy450')] = { model = 'energy450', price = 300000, banned = false, name = 'energy450', trunk = 100, type = 'vip'},
[GetHashKey('energyr1200')] = { model = 'energyr1200', price = 300000, banned = false, name = 'energyr1200', trunk = 100, type = 'vip'},
[GetHashKey('307c')] = { model = '307c', price = 300000, banned = false, name = '307c', trunk = 100, type = 'carro'},
[GetHashKey('370z')] = { model = '370z', price = 300000, banned = false, name = '370z', trunk = 100, type = 'vip'},
[GetHashKey('astonmartindbs')] = { model = 'astonmartindbs', price = 300000, banned = false, name = 'astonmartindbs', trunk = 100, type = 'vip'},
[GetHashKey('audir8')] = { model = 'audir8', price = 300000, banned = false, name = 'audir8', trunk = 100, type = 'vip'},
[GetHashKey('audirs')] = { model = 'audirs', price = 300000, banned = false, name = 'audirs', trunk = 100, type = 'vip'},
[GetHashKey('aventador')] = { model = 'aventador', price = 300000, banned = false, name = 'aventador', trunk = 100, type = 'vip'},
[GetHashKey('bmwi8')] = { model = 'bmwi8', price = 300000, banned = false, name = 'bmwi8', trunk = 100, type = 'vip'},
[GetHashKey('bmwm4gts')] = { model = 'bmwm4gts', price = 300000, banned = false, name = 'bmwm4gts', trunk = 100, type = 'vip'},
[GetHashKey('bmwm1wb')] = { model = 'bmwm1wb', price = 300000, banned = false, name = 'bmwm1wb', trunk = 100, type = 'vip'},
[GetHashKey('bmwm5e34')] = { model = 'bmwm5e34', price = 300000, banned = false, name = 'bmwm5e34', trunk = 100, type = 'vip'},
[GetHashKey('camaro')] = { model = 'camaro', price = 300000, banned = false, name = 'camaro', trunk = 100, type = 'vip'},
[GetHashKey('celta')] = { model = 'celta', price = 300000, banned = false, name = 'celta', trunk = 100, type = 'vip'},
[GetHashKey('160chumbo')] = { model = '160chumbo', price = 300000, banned = false, name = '160chumbo', trunk = 100, type = 'moto'},
[GetHashKey('chevette')] = { model = 'chevette', price = 300000, banned = false, name = 'chevette', trunk = 100, type = 'carro'},
[GetHashKey('city')] = { model = 'city', price = 600000, banned = false, name = 'city', trunk = 100, type = 'carro'},
[GetHashKey('civictyper')] = { model = 'civictyper', price = 300000, banned = false, name = 'civictyper', trunk = 100, type = 'vip'},
[GetHashKey('corvettec7')] = { model = 'corvettec7', price = 300000, banned = false, name = 'corvettec7', trunk = 100, type = 'vip'},
[GetHashKey('cruze')] = { model = 'cruze', price = 50000, banned = false, name = 'cruze', trunk = 100, type = 'carro'},
[GetHashKey('dodgechargerrt69')] = { model = 'dodgechargerrt69', price = 900000, banned = false, name = 'dodgechargerrt69', trunk = 100, type = 'vip'},
[GetHashKey('escaladegt900')] = { model = 'escaladegt900', price = 300000, banned = false, name = 'escaladegt900', trunk = 100, type = 'vip'},
[GetHashKey('dodgechargersrt')] = { model = 'dodgechargersrt', price = 300000, banned = false, name = 'dodgechargersrt', trunk = 100, type = 'vip'},
[GetHashKey('escort')] = { model = 'escort', price = 300000, banned = false, name = 'escort', trunk = 100, type = 'vip'},
[GetHashKey('ferrari812')] = { model = 'ferrari812', price = 300000, banned = false, name = 'ferrari812', trunk = 100, type = 'vip'},
[GetHashKey('ferrarif12')] = { model = 'ferrarif12', price = 300000, banned = false, name = 'ferrarif12', trunk = 100, type = 'vip'},
[GetHashKey('ferrariitalia')] = { model = 'ferrariitalia', price = 300000, banned = false, name = 'ferrariitalia', trunk = 100, type = 'vip'},
[GetHashKey('fiattoro')] = { model = 'fiattoro', price = 550000, banned = false, name = 'fiattoro', trunk = 100, type = 'vip'},
[GetHashKey('fusca')] = { model = 'fusca', price = 180000, banned = false, name = 'fusca', trunk = 100, type = 'carro'},
[GetHashKey('golquadrado')] = { model = 'golquadrado', price = 300000, banned = false, name = 'golquadrado', trunk = 100, type = 'vip'},
[GetHashKey('hb20')] = { model = 'hb20', price = 800000, banned = false, name = 'hb20', trunk = 100, type = 'vip'},
[GetHashKey('lamborghinihuracan')] = { model = 'lamborghinihuracan', price = 300000, banned = false, name = 'lamborghinihuracan', trunk = 100, type = 'vip'},
[GetHashKey('jettagli')] = { model = 'jettagli', price = 300000, banned = false, name = 'jettagli', trunk = 100, type = 'carro'},
[GetHashKey('lancerevolution9')] = { model = 'lancerevolution9', price = 300000, banned = false, name = 'lancerevolution9', trunk = 100, type = 'vip'},
[GetHashKey('m8competition')] = { model = 'm8competition', price = 300000, banned = false, name = 'm8competition', trunk = 100, type = 'vip'},
[GetHashKey('mazdarx7')] = { model = 'mazdarx7', price = 300000, banned = false, name = 'mazdarx7', trunk = 100, type = 'vip'},
[GetHashKey('opala')] = { model = 'opala', price = 500000, banned = false, name = 'opala', trunk = 100, type = 'carro'},
[GetHashKey('mustang1969')] = { model = 'mustang1969', price = 300000, banned = false, name = 'mustang1969', trunk = 100, type = 'vip'},
[GetHashKey('palio')] = { model = 'palio', price = 300000, banned = false, name = 'palio', trunk = 100, type = 'carro'},
[GetHashKey('panameramansory')] = { model = 'panameramansory', price = 300000, banned = false, name = 'panameramansory', trunk = 100, type = 'vip'},
[GetHashKey('parati')] = { model = 'parati', price = 500000, banned = false, name = 'parati', trunk = 100, type = 'carro'},
[GetHashKey('r1')] = { model = 'r1', price = 300000, banned = false, name = 'r1', trunk = 100, type = 'vip'},
[GetHashKey('r6')] = { model = 'r6', price = 300000, banned = false, name = 'r6', trunk = 100, type = 'vip'},
[GetHashKey('rangerover')] = { model = 'rangerover', price = 300000, banned = false, name = 'rangerover', trunk = 100, type = 'vip'},
[GetHashKey('s1000rr')] = { model = 's1000rr', price = 300000, banned = false, name = 's1000rr', trunk = 100, type = 'vip'},
[GetHashKey('saveirodeboxe')] = { model = 'saveirodeboxe', price = 300000, banned = false, name = 'saveirodeboxe', trunk = 100, type = 'vip'},
[GetHashKey('shelbygt500')] = { model = 'shelbygt500', price = 300000, banned = false, name = 'shelbygt500', trunk = 100, type = 'vip'},
[GetHashKey('silvias15')] = { model = 'silvias15', price = 300000, banned = false, name = 'silvias15', trunk = 100, type = 'vip'},
[GetHashKey('subarubrz')] = { model = 'subarubrz', price = 300000, banned = false, name = 'subarubrz', trunk = 100, type = 'vip'},
[GetHashKey('toyotasupra')] = { model = 'toyotasupra', price = 300000, banned = false, name = 'toyotasupra', trunk = 100, type = 'vip'},
[GetHashKey('toyotasupra2')] = { model = 'toyotasupra2', price = 300000, banned = false, name = 'toyotasupra2', trunk = 100, type = 'vip'},
[GetHashKey('uno')] = { model = 'uno', price = 150000, banned = false, name = 'uno', trunk = 100, type = 'caro'},
[GetHashKey('vwtouareg ')] = { model = 'vwtouareg ', price = 300000, banned = false, name = 'vwtouareg ', trunk = 100, type = 'carro'},
[GetHashKey('xj6')] = { model = 'xj6', price = 300000, banned = false, name = 'xj6', trunk = 100, type = 'vip'},
[GetHashKey('xre300')] = { model = 'xre300', price = 300000, banned = false, name = 'xre300', trunk = 100, type = 'vip'},
[GetHashKey('xt660')] = { model = 'xt660', price = 300000, banned = false, name = 'xt660', trunk = 100, type = 'vip'},
[GetHashKey('zx10r')] = { model = 'zx10r', price = 300000, banned = false, name = 'zx10r', trunk = 100, type = 'vip'},
[GetHashKey('rsq8mans')] = { model = 'rsq8mans', price = 300000, banned = false, name = 'RS8', trunk = 200, type = 'vip'},
[GetHashKey('cargobob')] = { model = 'cargobob', price = 300000, banned = false, name = 'cargobob', trunk = 800, type = 'none'},
[GetHashKey('luxor')] = { model = 'luxor', price = 300000, banned = false, name = 'luxor', trunk = 1000, type = 'none'},
[GetHashKey('shamal')] = { model = 'shamal', price = 300000, banned = false, name = 'shamal', trunk = 1000, type = 'none'},
[GetHashKey('titan')] = { model = 'titan', price = 300000, banned = false, name = 'titan', trunk = 10000, type = 'none'},
[GetHashKey('amarokpolicia')] = { model = 'amarokpolicia', price = nil, banned = false, name = 'Amarok DPD', trunk = 50, type = 'none'},
[GetHashKey('ambulance')] = { model = 'ambulance', price = 0, banned = false, name = 'Ambulancia', trunk = 50, type = 'none'},
[GetHashKey('sahpexplorer2')] = { model = 'sahpexplorer2', price = nil, banned = false, name = 'Ford Explore Médico', trunk = 50, type = 'none'},
[GetHashKey('mercedespolicia')] = { model = 'mercedespolicia', price = nil, banned = false, name = 'Mercedes DPD', trunk = 50, type = 'none'},
[GetHashKey('paramedicoheli')] = { model = 'paramedicoheli', price = nil, banned = false, name = 'Helicoptéro Médico', trunk = 50, type = 'none'},
[GetHashKey('pdfocus')] = { model = 'pdfocus', price = nil, banned = false, name = 'Ford Focus DPD', trunk = 50, type = 'none'},
[GetHashKey('tigerpolicia')] = { model = 'tigerpolicia', price = nil, banned = false, name = 'Tiger DPD', trunk = 30, type = 'none'},
[GetHashKey('polmav')] = { model = 'polmav', price = nil, banned = false, name = 'Helicoptero DPD', trunk = 50, type = 'none'},
[GetHashKey('trail20pm')] = { model = 'trail20pm', price = nil, banned = false, name = 'trail20pm', trunk = 50, type = 'none'},
[GetHashKey('tigerpm')] = { model = 'tigerpm', price = nil, banned = false, name = 'tigerpm', trunk = 50, type = 'none'},
[GetHashKey('s10pm')] = { model = 's10pm', price = nil, banned = false, name = 's10pm', trunk = 50, type = 'none'},
[GetHashKey('r1200pm ')] = { model = 'r1200pm ', price = nil, banned = false, name = 'r1200pm ', trunk = 50, type = 'none'},
[GetHashKey('polmav')] = { model = 'polmav', price = nil, banned = false, name = 'polmav', trunk = 50, type = 'none'},
[GetHashKey('pbus')] = { model = 'pbus', price = nil, banned = false, name = 'pbus', trunk = 50, type = 'none'},
[GetHashKey('pantera')] = { model = 'pantera', price = nil, banned = false, name = 'pantera', trunk = 50, type = 'none'},
[GetHashKey('dusterrp2')] = { model = 'dusterrp2', price = nil, banned = false, name = 'dusterrp2', trunk = 50, type = 'none'},
[GetHashKey('dusterrp1')] = { model = 'dusterrp1', price = nil, banned = false, name = 'dusterrp1', trunk = 50, type = 'none'},
[GetHashKey('s10rotam')] = { model = 's10rotam', price = nil, banned = false, name = 's10rotam', trunk = 50, type = 'none'},
[GetHashKey('equinoxprf')] = { model = 'equinoxprf', price = nil, banned = false, name = 's10rotam', trunk = 50, type = 'none'},
[GetHashKey('trail22prf')] = { model = 'trail22prf', price = nil, banned = false, name = 'trail22prf', trunk = 50, type = 'none'},
[GetHashKey('trail20prf')] = { model = 'trail20prf', price = nil, banned = false, name = 'trail20prf', trunk = 50, type = 'none'},
[GetHashKey('dusterpc')] = { model = 'dusterpc', price = nil, banned = false, name = 'dusterpc', trunk = 50, type = 'none'},
[GetHashKey('trail21pc')] = { model = 'trail21pc', price = nil, banned = false, name = 'trail21pc', trunk = 50, type = 'none'},
[GetHashKey('jeepcherokee')] = { model = 'jeepcherokee', price = nil, banned = false, name = 'jeepcherokee', trunk = 200, type = 'vip'},
[GetHashKey('supervolito')] = { model = 'supervolito', price = 300000, banned = false, name = 'Supervolito', trunk = 150, type = 'none'},
[GetHashKey('frogger')] = { model = 'frogger', price = 300000, banned = false, name = 'Frogger', trunk = 150, type = 'none'},
[GetHashKey('volatus')] = { model = 'volatus', price = 300000, banned = false, name = 'Volatus', trunk = 150, type = 'none'},
[GetHashKey('swift2')] = { model = 'swift2', price = 300000, banned = false, name = 'Swifit2', trunk = 150, type = 'none'},
[GetHashKey('phantom')] = { model = 'phantom', price = nil, banned = false, name = 'Phantom', trunk = nil, type = 'none'},
[GetHashKey('trash2')] = { model = 'trash2', price = nil, banned = false, name = 'Trash 2', trunk = nil, type = 'none'},
[GetHashKey('tiptruck')] = { model = 'tiptruck', price = nil, banned = false, name = 'Tip Truck', trunk = 80, type = 'none'},
[GetHashKey('boxville2')] = { model = 'boxville2', price = nil, banned = false, name = 'Box ville', trunk = 80, type = 'none'},
[GetHashKey('airbus')] = { model = 'airbus', price = nil, banned = false, name = 'Airbus', trunk = nil, type = 'none'},
[GetHashKey('bus')] = { model = 'bus', price = nil, banned = false, name = 'Bus', trunk = nil, type = 'none'},
[GetHashKey('coach')] = { model = 'coach', price = nil, banned = false, name = 'Coach', trunk = nil, type = 'none'},
[GetHashKey('dinghy')] = { model = 'dinghy', price = nil, banned = false, name = 'Dinghy', trunk = 50, type = 'none'},
[GetHashKey('trailerlogs')] = { model = 'trailerlogs', price = nil, banned = false, name = 'Trailer logs', trunk = 100, type = 'none'},
[GetHashKey('taxi')] = { model = 'taxi', price = nil, banned = false, name = 'Taxi', trunk = nil, type = 'none'},
[GetHashKey('towtruck2')] = { model = 'towtruck2', price = 0, banned = false, name = 'Guincho', trunk = 50, type = 'none'},
[GetHashKey('flatbed')] = { model = 'flatbed', price = 0, banned = false, name = 'flatbed', trunk = 10, type = 'none'},
[GetHashKey('golg4')] = { model = 'golg4', price = 300000, banned = false, name = 'golg4', trunk = 10, type = 'vip'},
[GetHashKey('s15silhouette')] = { model = 's15silhouette', price = 0, banned = false, name = 's15silhouette', trunk = 10, type = 'vip'},
[GetHashKey('-venatus')] = { model = '-venatus', price = 300000, banned = false, name = 'venatus', trunk = 10, type = 'vip'},
[GetHashKey('DBdemondurango')] = { model = 'DBdemondurango', price = 300000, banned = false, name = 'DBdemondurango', trunk = 10, type = 'vip'},
[GetHashKey('z1000')] = { model = 'z1000', price = 300000, banned = false, name = 'z1000', trunk = 10, type = 'vip'},
[GetHashKey('RYGBus')] = { model = 'RYGBus', price = 300000, banned = false, name = 'RYGBus', trunk = 10, type = 'vip'},
[GetHashKey('golf1')] = { model = 'golf1', price = 300000, banned = false, name = 'golf1', trunk = 10, type = 'vip'},
[GetHashKey('golf7')] = { model = 'golf7', price = 300000, banned = false, name = 'golf7', trunk = 10, type = 'vip'},
[GetHashKey('passat')] = { model = 'passat', price = 300000, banned = false, name = 'passat', trunk = 10, type = 'vip'},
[GetHashKey('specialtf')] = { model = 'specialtf', price = 300000, banned = false, name = 'specialtf', trunk = 10, type = 'vip'},
[GetHashKey('zl1')] = { model = 'zl1', price = 300000, banned = false, name = 'zl1', trunk = 10, type = 'vip'},
[GetHashKey('amarokreb')] = { model = 'amarokreb', price = 300000, banned = false, name = 'amarokreb', trunk = 10, type = 'vip'},
[GetHashKey('20xb7')] = { model = '20xb7', price = 300000, banned = false, name = '20xb7', trunk = 10, type = 'vip'},
[GetHashKey('GODzDRKHRSESBWB')] = { model = 'GODzDRKHRSESBWB', price = 300000, banned = false, name = 'GODzDRKHRSESBWB', trunk = 10, type = 'vip'},
[GetHashKey('20xb7')] = { model = '20xb7', price = 300000, banned = false, name = '20xb7', trunk = 10, type = 'vip'},
[GetHashKey('machewb')] = { model = 'machewb', price = 300000, banned = false, name = 'machewb', trunk = 10, type = 'vip'},
[GetHashKey('rrformulawide')] = { model = 'rrformulawide', price = 300000, banned = false, name = 'rrformulawide', trunk = 10, type = 'vip'},
[GetHashKey('gcmlamboultimae')] = { model = 'gcmlamboultimae', price = 300000, banned = false, name = 'gcmlamboultimae', trunk = 10, type = 'vip'},
[GetHashKey('h2m')] = { model = 'h2m', price = 300000, banned = false, name = 'h2m', trunk = 10, type = 'vip'},
[GetHashKey('fk8')] = { model = 'fk8', price = 300000, banned = false, name = 'fk8', trunk = 10, type = 'vip'},
[GetHashKey('jes21')] = { model = 'jes21', price = 300000, banned = false, name = 'jes21', trunk = 10, type = 'vip'},
[GetHashKey('senna')] = { model = 'senna', price = 300000, banned = false, name = 'senna', trunk = 10, type = 'vip'},
[GetHashKey('-G63Sam')] = { model = '-G63Sam', price = 300000, banned = false, name = '-G63Sam', trunk = 10, type = 'vip'},
[GetHashKey('CarsonsHycadeR35')] = { model = 'CarsonsHycadeR35', price = 300000, banned = false, name = 'CarsonsHycadeR35', trunk = 10, type = 'vip'},
[GetHashKey('nismo20')] = { model = 'nismo20', price = 300000, banned = false, name = 'nismo20', trunk = 10, type = 'vip'},
[GetHashKey('s15lunarr')] = { model = 's15lunarr', price = 300000, banned = false, name = 's15lunarr', trunk = 10, type = 'vip'},
[GetHashKey('r36fp')] = { model = 'r36fp', price = 300000, banned = false, name = 'r36fp', trunk = 10, type = 'vip'},
[GetHashKey('r35legend')] = { model = 'r35legend', price = 300000, banned = false, name = 'r35legend', trunk = 10, type = 'vip'},
[GetHashKey('silvia666')] = { model = 'silvia666', price = 300000, banned = false, name = 'silvia666', trunk = 10, type = 'vip'},
[GetHashKey('aerox155')] = { model = 'aerox155', price = 300000, banned = false, name = 'aerox155', trunk = 10, type = 'vip'},
[GetHashKey('bati901')] = { model = 'bati901', price = 300000, banned = false, name = 'bati901', trunk = 10, type = 'vip'},
[GetHashKey('cb650r')] = { model = 'cb650r', price = 300000, banned = false, name = 'cb650r', trunk = 10, type = 'vip'},
[GetHashKey('21rsq8')] = { model = '21rsq8', price = 300000, banned = false, name = '21rsq8', trunk = 10, type = 'vip'},
[GetHashKey('74civrswb')] = { model = '74civrswb', price = 300000, banned = false, name = '74civrswb', trunk = 10, type = 'vip'},
[GetHashKey('q8hycade')] = { model = 'q8hycade', price = 300000, banned = false, name = 'q8hycade', trunk = 10, type = 'vip'},
[GetHashKey('rs4rk')] = { model = 'rs4rk', price = 300000, banned = false, name = 'rs4rk', trunk = 10, type = 'vip'},
[GetHashKey('rs5mans')] = { model = 'rs5mans', price = 300000, banned = false, name = 'rs5mans', trunk = 10, type = 'vip'},
[GetHashKey('m3e92')] = { model = 'm3e92', price = 300000, banned = false, name = 'm3e92', trunk = 10, type = 'vip'},
[GetHashKey('ddc69maro')] = { model = 'ddc69maro', price = 300000, banned = false, name = 'ddc69maro', trunk = 10, type = 'vip'},
[GetHashKey('chironsuper')] = { model = 'chironsuper', price = 300000, banned = false, name = 'chironsuper', trunk = 10, type = 'vip'},
[GetHashKey('ckbmwm4offwhite')] = { model = 'ckbmwm4offwhite', price = 300000, banned = false, name = 'ckbmwm4offwhite', trunk = 10, type = 'vip'},
[GetHashKey('rmodcharger')] = { model = 'rmodcharger', price = 300000, banned = false, name = 'rmodcharger', trunk = 10, type = 'vip'},
[GetHashKey('chargerf8')] = { model = 'chargerf8', price = 300000, banned = false, name = 'chargerf8', trunk = 10, type = 'vip'},
[GetHashKey('hellcatf9')] = { model = 'hellcatf9', price = 300000, banned = false, name = 'hellcatf9', trunk = 10, type = 'vip'},
[GetHashKey('q8prior')] = { model = 'q8prior', price = 300000, banned = false, name = 'q8prior', trunk = 10, type = 'vip'},
[GetHashKey('amarok')] = { model = 'amarok', price = 300000, banned = false, name = 'amarok', trunk = 10, type = 'vip'},
[GetHashKey('160chumbo')] = { model = '160chumbo', price = 300000, banned = false, name = '160chumbo', trunk = 10, type = 'vip'},
[GetHashKey('samumav')] = { model = 'samumav', price = 300000, banned = false, name = 'samumav', trunk = 10, type = 'vip'},
[GetHashKey('r1200')] = { model = 'r1200', price = 300000, banned = false, name = 'r1200', trunk = 10000, type = 'vip'},
[GetHashKey('trenonatal')] = { model = 'trenonatal', price = 300000, banned = false, name = 'trenonatal', trunk = 10000, type = 'vip'},
[GetHashKey('chevroletnatal')] = { model = 'chevroletnatal', price = 300000, banned = false, name = 'chevroletnatal', trunk = 10000, type = 'vip'},
[GetHashKey('xre2019')] = { model = 'xre2019', price = 300000, banned = false, name = 'xre2019', trunk = 10000, type = 'vip'},
[GetHashKey('pop110i')] = { model = 'pop110i', price = 300000, banned = false, name = 'pop110i', trunk = 10000, type = 'vip'},
[GetHashKey('18performante')] = { model = '18performante', price = 300000, banned = false, name = '18performante', trunk = 10000, type = 'vip'},
[GetHashKey('350z')] = { model = '350z', price = 300000, banned = false, name = '350z', trunk = 10000, type = 'vip'},
[GetHashKey('675lt')] = { model = '675lt', price = 300000, banned = false, name = '675lt', trunk = 10000, type = 'vip'},
[GetHashKey('2022jeep')] = { model = '2022jeep', price = 300000, banned = false, name = '2022jeep', trunk = 10000, type = 'vip'},
[GetHashKey('a45')] = { model = 'a45', price = 300000, banned = false, name = 'a45', trunk = 10000, type = 'vip'},
[GetHashKey('aerox155')] = { model = 'aerox155', price = 300000, banned = false, name = 'aerox155', trunk = 10000, type = 'vip'},
[GetHashKey('amaroksimples')] = { model = 'amaroksimples', price = 300000, banned = false, name = 'amaroksimples', trunk = 10000, type = 'vip'},
[GetHashKey('brzartisan')] = { model = 'brzartisan', price = 300000, banned = false, name = 'brzartisan', trunk = 10000, type = 'vip'},
[GetHashKey('carrera19')] = { model = 'carrera19', price = 300000, banned = false, name = 'carrera19', trunk = 10000, type = 'vip'},
[GetHashKey('claw')] = { model = 'claw', price = 300000, banned = false, name = 'claw', trunk = 10000, type = 'vip'},
[GetHashKey('evo9')] = { model = 'evo9', price = 300000, banned = false, name = 'evo9', trunk = 10000, type = 'vip'},
[GetHashKey('fpaceprior')] = { model = 'fpaceprior', price = 300000, banned = false, name = 'fpaceprior', trunk = 10000, type = 'vip'},
[GetHashKey('g63c')] = { model = 'g63c', price = 300000, banned = false, name = 'g63c', trunk = 10000, type = 'vip'},
[GetHashKey('GC_01INTEG')] = { model = 'GC_01INTEG', price = 300000, banned = false, name = 'GC_01INTEG', trunk = 10000, type = 'vip'},
[GetHashKey('gcma4sedan2021')] = { model = 'gcma4sedan2021', price = 300000, banned = false, name = 'gcma4sedan2021', trunk = 10000, type = 'vip'},
[GetHashKey('GODz300UTEHC')] = { model = 'GODz300UTEHC', price = 300000, banned = false, name = 'GODz300UTEHC', trunk = 10000, type = 'vip'},
[GetHashKey('GODzBMWS1000RR')] = { model = 'GODzBMWS1000RR', price = 300000, banned = false, name = 'GODzBMWS1000RR', trunk = 10000, type = 'vip'},
[GetHashKey('GODzNINJAH2')] = { model = 'GODzNINJAH2', price = 300000, banned = false, name = 'GODzNINJAH2', trunk = 10000, type = 'vip'},
[GetHashKey('GODzRB26SUBI')] = { model = 'GODzRB26SUBI', price = 300000, banned = false, name = 'GODzRB26SUBI', trunk = 10000, type = 'vip'},
[GetHashKey('GODzYAMR1')] = { model = 'GODzYAMR1', price = 300000, banned = false, name = 'GODzYAMR1', trunk = 10000, type = 'vip'},
[GetHashKey('gt63mt')] = { model = 'gt63mt', price = 300000, banned = false, name = 'gt63mt', trunk = 10000, type = 'vip'},
[GetHashKey('gta5rp_veh_gtr33')] = { model = 'gta5rp_veh_gtr33', price = 300000, banned = false, name = 'gta5rp_veh_gtr33', trunk = 10000, type = 'vip'},
[GetHashKey('harleyfx')] = { model = 'harleyfx', price = 300000, banned = false, name = 'harleyfx', trunk = 10000, type = 'vip'},
[GetHashKey('hexerz2')] = { model = 'hexerz2', price = 300000, banned = false, name = 'hexerz2', trunk = 10000, type = 'vip'},
[GetHashKey('huracanpriorbeast')] = { model = 'huracanpriorbeast', price = 300000, banned = false, name = 'huracanpriorbeast', trunk = 10000, type = 'vip'},
[GetHashKey('hyundaiveloster')] = { model = 'hyundaiveloster', price = 300000, banned = false, name = 'hyundaiveloster', trunk = 10000, type = 'vip'},
[GetHashKey('ikx3abt20')] = { model = 'ikx3abt20', price = 300000, banned = false, name = 'ikx3abt20', trunk = 10000, type = 'vip'},
[GetHashKey('ikx3mc2021')] = { model = 'ikx3mc2021', price = 300000, banned = false, name = 'ikx3mc2021', trunk = 10000, type = 'vip'},
[GetHashKey('ikx3rebel22')] = { model = 'ikx3rebel22', price = 300000, banned = false, name = 'ikx3rebel22', trunk = 10000, type = 'vip'},
[GetHashKey('kawagala')] = { model = 'kawagala', price = 300000, banned = false, name = 'kawagala', trunk = 10000, type = 'vip'},
[GetHashKey('km1000rr')] = { model = 'km1000rr', price = 300000, banned = false, name = 'km1000rr', trunk = 10000, type = 'vip'},
[GetHashKey('lc500')] = { model = 'lc500', price = 300000, banned = false, name = 'lc500', trunk = 10000, type = 'vip'},
[GetHashKey('madf350lift')] = { model = 'madf350lift', price = 300000, banned = false, name = 'madf350lift', trunk = 10000, type = 'vip'},
[GetHashKey('mansgt')] = { model = 'mansgt', price = 300000, banned = false, name = 'mansgt', trunk = 10000, type = 'none'},
[GetHashKey('manssupersnake')] = { model = 'manssupersnake', price = 300000, banned = false, name = 'manssupersnake', trunk = 10000, type = 'vip'},
[GetHashKey('model3')] = { model = 'model3', price = 300000, banned = false, name = 'model3', trunk = 10000, type = 'vip'},
[GetHashKey('models')] = { model = 'models', price = 300000, banned = false, name = 'models', trunk = 10000, type = 'vip'},
[GetHashKey('mv2019')] = { model = 'mv2019', price = 300000, banned = false, name = 'mv2019', trunk = 10000, type = 'vip'},
[GetHashKey('nsx17')] = { model = 'nsx17', price = 300000, banned = false, name = 'nsx17', trunk = 10000, type = 'vip'},
[GetHashKey('polestar1')] = { model = 'polestar1', price = 300000, banned = false, name = 'polestar1', trunk = 10000, type = 'vip'},
[GetHashKey('rmodjeepg')] = { model = 'rmodjeepg', price = 300000, banned = false, name = 'rmodjeepg', trunk = 10000, type = 'vip'},
[GetHashKey('rmodpagani')] = { model = 'rmodpagani', price = 300000, banned = false, name = 'rmodpagani', trunk = 10000, type = 'vip'},
[GetHashKey('rmodr8alpil')] = { model = 'rmodr8alpil', price = 300000, banned = false, name = 'rmodr8alpil', trunk = 10000, type = 'vip'},
[GetHashKey('rmodx6')] = { model = 'rmodx6', price = 300000, banned = false, name = 'rmodx6', trunk = 10000, type = 'vip'},
[GetHashKey('sex6')] = { model = 'sex6', price = 300000, banned = false, name = 'sex6', trunk = 10000, type = 'vip'},
[GetHashKey('sinacp')] = { model = 'sinacp', price = 300000, banned = false, name = 'sinacp', trunk = 10000, type = 'vip'},
[GetHashKey('taycanani')] = { model = 'taycanani', price = 300000, banned = false, name = 'taycanani', trunk = 10000, type = 'vip'},
[GetHashKey('v60hr')] = { model = 'v60hr', price = 300000, banned = false, name = 'v60hr', trunk = 10000, type = 'vip'},
[GetHashKey('waldw222')] = { model = 'waldw222', price = 300000, banned = false, name = 'waldw222', trunk = 10000, type = 'vip'},
[GetHashKey('wheelchair')] = { model = 'wheelchair', price = 300000, banned = false, name = 'wheelchair', trunk = 10000, type = 'vip'},
[GetHashKey('yzfr7')] = { model = 'yzfr7', price = 300000, banned = false, name = 'yzfr7', trunk = 10000, type = 'vip'},
[GetHashKey('z8r')] = { model = 'z8r', price = 300000, banned = false, name = 'z8r', trunk = 10000, type = 'vip'},
[GetHashKey('zentenario')] = { model = 'zentenario', price = 300000, banned = false, name = 'zentenario', trunk = 10000, type = 'vip'},
[GetHashKey('choilambo')] = { model = 'choilambo', price = 300000, banned = false, name = 'choilambo', trunk = 10000, type = 'vip'},
[GetHashKey('fxho')] = { model = 'fxho', price = 300000, banned = false, name = 'fxho', trunk = 10000, type = 'vip'},
[GetHashKey('motosamu')] = { model = 'motosamu', price = 300000, banned = false, name = 'motosamu', trunk = 10000, type = 'vip'},
[GetHashKey('sprintersamu')] = { model = 'sprintersamu', price = 300000, banned = false, name = 'sprintersamu', trunk = 10000, type = 'vip'},
[GetHashKey('enladder')] = { model = 'enladder', price = 300000, banned = false, name = 'enladder', trunk = 10000, type = 'vip'},
[GetHashKey('blista')] = { model = 'blista', price = 300000, banned = false, name = 'blista', trunk = 10000, type = 'vip'},
[GetHashKey('l20021')] = { model = 'l20021', price = 300000, banned = false, name = 'l20021', trunk = 10000, type = 'vip'},
[GetHashKey('xxxxx')] = { model = 'xxxxx', price = 300000, banned = false, name = 'xxxxx', trunk = 10000, type = 'vip'},
[GetHashKey('renaultcbm')] = { model = 'renaultcbm', price = 300000, banned = false, name = 'renaultcbm', trunk = 10000, type = 'vip'},
[GetHashKey('NBFiretruck')] = { model = 'NBFiretruck', price = 300000, banned = false, name = 'NBFiretruck', trunk = 10000, type = 'vip'},
[GetHashKey('trail22grau')] = { model = 'trail22grau', price = 300000, banned = false, name = 'trail22grau', trunk = 10000, type = 'vip'},
[GetHashKey('xt660cb2')] = { model = 'xt660cb2', price = 300000, banned = false, name = 'xt660cb2', trunk = 10000, type = 'vip'},
[GetHashKey('savapikachu')] = { model = 'savapikachu', price = 300000, banned = false, name = 'savapikachu', trunk = 10000, type = 'vip'},
[GetHashKey('tenere')] = { model = 'tenere', price = 300000, banned = false, name = 'tenere', trunk = 10000, type = 'vip'},
[GetHashKey('golsupreme')] = { model = 'golsupreme', price = 300000, banned = false, name = 'golsupreme', trunk = 10000, type = 'vip'},
[GetHashKey('unofirma')] = { model = 'unofirma', price = 300000, banned = false, name = 'unofirma', trunk = 10000, type = 'vip'},
[GetHashKey('BC_Escaladeprime')] = { model = 'BC_Escaladeprime', price = 300000, banned = false, name = 'BC_Escaladeprime', trunk = 10000, type = 'vip'},
[GetHashKey('s15')] = { model = 's15', price = 300000, banned = false, name = 's15', trunk = 10000, type = 'vip'},
[GetHashKey('bmas350')] = { model = 'bmas350', price = 300000, banned = false, name = 'bmas350', trunk = 10000, type = 'vip'},
[GetHashKey('mansoryg63')] = { model = 'mansoryg63', price = 300000, banned = false, name = 'mansoryg63', trunk = 10000, type = 'vip'},
[GetHashKey('as350samu')] = { model = 'as350samu', price = 300000, banned = false, name = 'as350samu', trunk = 10000, type = 'vip'},
[GetHashKey('f250abel')] = { model = 'f250abel', price = 300000, banned = false, name = 'f250abel', trunk = 10000, type = 'vip'},
[GetHashKey('trdrw')] = { model = 'trdrw', price = 300000, banned = false, name = 'trdrw', trunk = 10000, type = 'vip'},
[GetHashKey('GODz95GSX')] = { model = 'GODz95GSX', price = 300000, banned = false, name = 'GODz95GSX', trunk = 10000, type = 'vip'},
[GetHashKey('BC_MercedesGT63')] = { model = 'BC_MercedesGT63', price = 300000, banned = false, name = 'BC_MercedesGT63', trunk = 10000, type = 'vip'},
[GetHashKey('silva')] = { model = 'silva', price = 300000, banned = false, name = 'silva', trunk = 10000, type = 'vip'},
[GetHashKey('explorer')] = { model = 'explorer', price = 300000, banned = false, name = 'explorer', trunk = 10000, type = 'vip'},
[GetHashKey('explorer')] = { model = 'explorer', price = 300000, banned = false, name = 'explorer', trunk = 10000, type = 'vip'},
[GetHashKey('agerasuper')] = { model = 'agerasuper', price = 300000, banned = false, name = 'agerasuper', trunk = 10000, type = 'vip'},
[GetHashKey('jeslbwk')] = { model = 'jeslbwk', price = 300000, banned = false, name = 'jeslbwk', trunk = 10000, type = 'vip'},
[GetHashKey('hornet')] = { model = 'hornet', price = 300000, banned = false, name = 'hornet', trunk = 10000, type = 'vip'},
[GetHashKey('lrvelar')] = { model = 'lrvelar', price = 300000, banned = false, name = 'lrvelar', trunk = 10000, type = 'vip'},
[GetHashKey('a29bst')] = { model = 'a29bst', price = 300000, banned = false, name = 'a29bst', trunk = 10000, type = 'vip'},
[GetHashKey('mh60k')] = { model = 'mh60k', price = 300000, banned = false, name = 'mh60k', trunk = 10000, type = 'vip'},
[GetHashKey('eb350')] = { model = 'eb350', price = 300000, banned = false, name = 'eb350', trunk = 10000, type = 'vip'},
[GetHashKey('gripene')] = { model = 'gripene', price = 300000, banned = false, name = 'gripene', trunk = 10000, type = 'vip'},
[GetHashKey('cg130h')] = { model = 'cg130h', price = 300000, banned = false, name = 'cg130h', trunk = 10000, type = 'vip'},
[GetHashKey('mh65c')] = { model = 'mh65c', price = 300000, banned = false, name = 'mh65c', trunk = 10000, type = 'vip'},
[GetHashKey('ec725')] = { model = 'ec725', price = 300000, banned = false, name = 'ec725', trunk = 10000, type = 'vip'},
[GetHashKey('Mammatus')] = { model = 'Mammatus', price = 300000, banned = false, name = 'Mammatus', trunk = 10000, type = 'vip'},
[GetHashKey('m939')] = { model = 'm939', price = 300000, banned = false, name = 'm939', trunk = 10000, type = 'vip'},
[GetHashKey('ambeb')] = { model = 'ambeb', price = 300000, banned = false, name = 'ambeb', trunk = 10000, type = 'vip'},
[GetHashKey('harleype')] = { model = 'harleype', price = 300000, banned = false, name = 'harleype', trunk = 10000, type = 'vip'},
[GetHashKey('terrex')] = { model = 'terrex', price = 300000, banned = false, name = 'terrex', trunk = 10000, type = 'vip'},
[GetHashKey('hilux')] = { model = 'hilux', price = 300000, banned = false, name = 'hilux', trunk = 10000, type = 'vip'},
[GetHashKey('hiluxgaiola')] = { model = 'hiluxgaiola', price = 300000, banned = false, name = 'hiluxgaiola', trunk = 10000, type = 'vip'},
[GetHashKey('l200eb2')] = { model = 'l200eb2', price = 300000, banned = false, name = 'l200eb2', trunk = 10000, type = 'vip'},
[GetHashKey('m113')] = { model = 'm113', price = 300000, banned = false, name = 'm113', trunk = 10000, type = 'vip'},
[GetHashKey('agrale')] = { model = 'agrale', price = 300000, banned = false, name = 'agrale', trunk = 10000, type = 'vip'},
[GetHashKey('agraletransporte')] = { model = 'agraletransporte', price = 300000, banned = false, name = 'agraletransporte', trunk = 10000, type = 'vip'},
[GetHashKey('nc750xembu')] = { model = 'nc750xembu', price = 300000, banned = false, name = 'nc750xembu', trunk = 10000, type = 'vip'},
[GetHashKey('pajerope')] = { model = 'pajerope', price = 300000, banned = false, name = 'pajerope', trunk = 10000, type = 'vip'},
[GetHashKey('flatbed3')] = { model = 'flatbed3', price = 300000, banned = false, name = 'flatbed3', trunk = 10000, type = 'vip'},
[GetHashKey('xrepe')] = { model = 'xrepe', price = 300000, banned = false, name = 'xrepe', trunk = 10000, type = 'vip'},
[GetHashKey('bxstorecybertruckv')] = { model = 'bxstorecybertruckv', price = 300000, banned = false, name = 'bxstorecybertruckv', trunk = 10000, type = 'vip'},
[GetHashKey('bell412bxstore')] = { model = 'bell412bxstore', price = 300000, banned = false, name = 'bell412bxstore', trunk = 10000, type = 'vip'},
[GetHashKey('bm320ibxstore')] = { model = 'bm320ibxstore', price = 300000, banned = false, name = 'bm320ibxstore', trunk = 10000, type = 'vip'},
[GetHashKey('bxstoreeurus')] = { model = 'bxstoreeurus', price = 300000, banned = false, name = 'bxstoreeurus', trunk = 10000, type = 'vip'},
[GetHashKey('bxstorefsf90xx')] = { model = 'bxstorefsf90xx', price = 300000, banned = false, name = 'bxstorefsf90xx', trunk = 10000, type = 'vip'},
[GetHashKey('bxstoretiggo8')] = { model = 'bxstoretiggo8', price = 300000, banned = false, name = 'bxstoretiggo8', trunk = 10000, type = 'vip'},
[GetHashKey('bxstorex6')] = { model = 'bxstorex6', price = 300000, banned = false, name = 'bxstorex6', trunk = 10000, type = 'vip'},
[GetHashKey('bxstorex7')] = { model = 'bxstorex7', price = 300000, banned = false, name = 'bxstorex7', trunk = 10000, type = 'vip'},
[GetHashKey('bxstorext660r')] = { model = 'bxstorext660r', price = 300000, banned = false, name = 'bxstorext660r', trunk = 10000, type = 'vip'},
[GetHashKey('corollabxstorexcoldgg')] = { model = 'corollabxstorexcoldgg', price = 300000, banned = false, name = 'corollabxstorexcoldgg', trunk = 10000, type = 'vip'},
[GetHashKey('gle63bxstore')] = { model = 'gle63bxstore', price = 300000, banned = false, name = 'gle63bxstore', trunk = 10000, type = 'vip'},
[GetHashKey('l200bxstore')] = { model = 'l200bxstore', price = 300000, banned = false, name = 'l200bxstore', trunk = 10000, type = 'vip'},
[GetHashKey('rs62bxstore')] = { model = 'rs62bxstore', price = 300000, banned = false, name = 'rs62bxstore', trunk = 10000, type = 'vip'},
[GetHashKey('traiblaze17bxstore')] = { model = 'traiblaze17bxstore', price = 300000, banned = false, name = 'traiblaze17bxstore', trunk = 10000, type = 'vip'},
[GetHashKey('x7bxstore')] = { model = 'x7bxstore', price = 300000, banned = false, name = 'x7bxstore', trunk = 10000, type = 'vip'},
[GetHashKey('HellcatRed')] = { model = 'HellcatRed', price = 300000, banned = false, name = 'HellcatRed', trunk = 10000, type = 'vip'},
[GetHashKey('vironmichalski')] = { model = 'vironmichalski', price = 300000, banned = false, name = 'vironmichalski', trunk = 10000, type = 'vip'},
[GetHashKey('cbtwister22k')] = { model = 'cbtwister22k', price = 300000, banned = false, name = 'cbtwister22k', trunk = 10000, type = 'vip'},
